<?php
$_POST['page'] = "pirate.php";
include 'head.php';

echo '<title>Pirate Memories</title>';

include 'sidebar.php';

echo "	<section>	
			<article>
				<h1>Pirate Memories</h1>
					<p>It all started when our over-heralded star, Spencer, woke up in a bush. It was t' fifth time it had happened. Feelin' abnormally displeased, Spencer stroked a gerbil, thinkin' it would make him feel better (but as usual, it did not). Happy as a frickin' monkey, he realized that his beloved Magic Keyboard was missin'! Immediately he called his so-called buddy, Serah. Spencer had known Serah for (plus or minus) 61 years, t' majority o' which were eccentric ones. Serah was unique. She was easygoin' though sometimes a little... stupid. Spencer called her anyway, for t' situation was urgent.</p>
					<p>Serah picked up t' a very happy Spencer. Serah calmly asayed him that most Indonesian devil cats belch before matin', yet long-haired sea monkeys usually exotically shudder *after* matin'. She had no idea what that meant; she was only concerned with distractin' Spencer. Why was Serah tryin' t' distract Spencer? Because she had snuck out from Spencer's with t' Magic Keyboard only eight days prior. It was a enchantin' little Magic Keyboard... how could she resist?</p>
					<p>It didn't take long before Spencer got aft t' t' subject at hand: his Magic Keyboard. Serah sighed. Reluctantly, Serah invited him over, assurin' him they'd find t' Magic Keyboard. Spencer grabbed his canoe and disembarked immediately. After hangin' up t' phone, Serah realized that she was in trouble. She had t' find a place t' hide t' Magic Keyboard and she had t' do it skillfully. She figured that if Spencer took t' 'modded' Civic, , she had take at least seven minutes before Spencer would get thar. But if he took t' hoverboat? Then Serah would be ridiculously screwed.</p>
					<p>Before she could come up with any reasonable ideas, Serah was interrupted by four clueless penguins that were lured by her Magic Keyboard. Serah turned red; 'Not again', she thought. Feelin' displeased, she randomly reached for her gerbil and recklessly poked every last one o' them. Apparently this was an adequate deterrent--t' discouraged critters began t' scurry aft toward t' haunted thicket, squealin' with discontent. She exhaled with relief. That's when she heard t' hoverboat rollin' up. It was Spencer.</p>
					<p>As he pulled up, he felt a sense o' urgency. He had had t' make an unscheduled stop at Texaco t' pick up a 12-pack o' dangerous oil-soaked rags, so he knew he was runnin' late. With a quick leap, Spencer was out o' t' hoverboat and went charismatically jauntin' toward Serah's fore door. Meanwhile inside, Serah was panickin'. Not thinkin', she tossed t' Magic Keyboard into a box o' dull pencils and then slid t' box behind her canoe. Serah was angered but at least t' Magic Keyboard was concealed. T' doorbell rang.</p>
					<p>Come in,' Serah wildly purred. With a careful push, Spencer opened t' door. 'Sorry for bein' late, but I was bein' chased by some abrasive self-starboardeous butt in a Jap Trap,' he lied. 'Its fine,' Serah asayed him. Spencer took a seat vaguely close t' where Serah had hidden t' Magic Keyboard. Serah grimaced tryin' unsuccessfully t' hide her nervousness. 'Uhh, can I get you anythin'?' she blurted. But Spencer was distracted. Just as zero people expected Serah noticed a insensitive look on Spencer's face. Spencer slowly opened his mouth t' speak.</p>
					<p>'...What's that smell?'</p>
					<p>Serah felt a stabbin' pain in her ear when Spencer asked this. In a moment o' disbelief, she realized that she had hidden t' Magic Keyboard starboard by her oscillatin' fan. 'Wh-what? I don't smell anythin'..!' A lie. A annoyin' look started t' form on Spencer's face. He turned t' notice a box that seemed clearly out o' place. 'Th-th-those be just me grandma's live hand grenades from when she used t' have pet man-eatin' capybaras. She, uh...dropped 'em by here earlier' Spencer nodded with fake acknowledgement...then, before Serah could react, Spencer aimlessly lunged toward t' box and opened it. T' Magic Keyboard was plainly in view.</p>
					<p>Spencer stared at Serah for what what must've been six seconds. Duly ecstatic about t' loomin' crises, Serah groped indiscriminately in Spencer's direction, clearly desperate. Spencer grabbed t' Magic Keyboard and bolted for t' door. It was locked. Serah let out a saucy chuckle. 'If only you hadn't been so protective o' that thin', none o' this would have happened, Spencer,' she rebuked. Serah always had been a little clueless, so Spencer knew that reconciliation was not an option; he needed t' escape before Serah did somethin' crazy, like... start chuckin' gerbils at her or somethin'. Duly ecstatic about t' loomin' crises, he gripped his Magic Keyboard tightly and made a dash toward t' window, divin' headlong through t' glass panels.</p>
					<p>Serah looked on, blankly. 'What t' heck? That seemed excessive. T' other door was open, you know.' Silence from Spencer. 'And t' think, I varnished that window frame eight days ago...it never ends!' Suddenly she felt a tin'e o' concern for Spencer. 'Oh. You ..okay?' Still silence. Serah walked over t' t' window and looked down. Spencer was gone.</p>
					<p>Just yonder, Spencer was strugglin' t' make his way through t' haunted thicket behind Serah's place. Spencer had severely hurt his prostate durin' t' window incident, and was startin' t' lose strength. Another pack o' feral penguins suddenly appeared, havin' caught wind o' t' Magic Keyboard. One by one they latched on t' Spencer. Already weakened from his injury, Spencer yielded t' t' furry onslaught and collapsed. T' last thin' he saw before losin' consciousness was a buzzin' horde o' penguins runnin' off with his Magic Keyboard.</p>
					<p>About five hours later, Spencer awoke, his double chin throbbin'. It was dark and Spencer did not know where he was. Deep in t' uninhabited disease-infested jungle, Spencer was excessively lost. A few unfulfilled decades later, he remembered that his Magic Keyboard was taken by t' penguins. But at that point, he was just thankful for his life. That's when, t' his horror, a huge penguin emerged from t' foxy forest. It was t' alpha penguin. Spencer opened his mouth t' scream but was cut short when t' penguin sunk its teeth into Spencer's fin'ernail. With a faint groan, t' life escaped from Spencer's lungs, but not before he realized that he was a failure.</p>
					<p>Less than five miles away, Serah was entombed by anguish over t' loss o' t' Magic Keyboard. 'me PRECIOUS!!' she cried, as she reached for a sharpened ninja star. With an apt thrust, she buried it deeply into her taint. As t' room began t' fade t' black, she thought about Spencer... wishin' she had found t' courage t' tell him that she loved him. But she would die alone that day. All that remained was t' Magic Keyboard that had turned them against each other, ultimately causin' their demise. And as t' dew on melancholy saplin' branches began t' reflect t' dawn's reddish glare all that could be heard was t' chillin' cry o' distant penguins, desecratin' all thin's sacred t' virtuous men, and perpetuatin an evil that would reign for centuries t' come. Our heroes would've lived unhappily ever after, but they were too busy bein' went t' Davy Jones' locker. So, no one lived forever after, t' end</p>
			</article>
		</section>";
		
include 'footer.php';
?>